### ISSUE TITLE
qss v0.0.4 not compatible with HA 2023.06+

### ISSUE THREAD

**Issue by saintman23** [CM000n/qss#6]
**Describe the bug**
QSS integration not starting giving error:

Эта ошибка возникла в пользовательской интеграции.

Logger: homeassistant.loader
Source: custom_components/qss/io.py:8
Integration: qss (documentation, issues)
First occurred: 00:34:50 (1 occurrences)
Last logged: 00:34:50

Unexpected exception importing component custom_components.qss
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/qss/__init__.py", line 38, in <module>
    from .io import insert_event_data_into_questdb
  File "/config/custom_components/qss/io.py", line 8, in <module>
    from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_fixed
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 451, in <module>
    from tenacity._asyncio import AsyncRetrying
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 33, in <module>
    class AsyncRetrying(BaseRetrying):
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 41, in AsyncRetrying
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**To Reproduce**
start HA

**Expected behavior**
loading with HA

Probably issue is connected to python 3..11

**Comment by mgumz** [comment]
hassio:2023.06.2
qss:0.0.4

the culprit is python3.11, the deprecation of certain decorators as they are used in one of qss deps: tenacity. the manifest.json states a version between 5 and 6 should be used. available is tenacity:8.x, among various fixes is also improved handling of python 3.10 and 3.11.

so, i tried this:

```
{
    "codeowners": [
        "@CM000n"
    ],
    "dependencies": [],
    "documentation": "https://github.com/CM000n/QSS",
    "domain": "qss",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/CM000n/QSS/issues",
    "name": "QuestDB State Storage (QSS)",
    "requirements": [
        "questdb>=1.0,<2.0",
        "tenacity>=8.2"
    ],
    "version": "0.0.4"
}
```

i changed the required tenacity version to require at least 8.2 … and now i see my data in questdb again.

**Comment by mgumz** [comment]
@saintman23 you might wanne try https://github.com/CM000n/qss/pull/7

**Comment by CM000n** [comment]
Once again, thank you very much @mgumz.
Problem should be solved with https://github.com/CM000n/qss/releases/tag/v0.0.5 @saintman23.
Can you please check and report back?

**Comment by saintman23** [comment]
v0.0.6 loads ok on HA 2023.6.3
